version: "3"
services:
  chromium:
    image: sassmann/debian-chromium:latest 
    environment:
      - DISPLAY
    volumes:
      - /var/opt/.X11-unix:/tmp/.X11-unix:ro
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "80:80"
      - "443:443"
      - "22:22"