version: "2"
services:
  sshd:
    build: images/sshd
    environment:
      - ID_RSA_PUB
  personal:
    build: images/cloud9
    environment:
      - DISPLAY
      - ID_RSA
      - ID_RSA_PUB
      - KNOWN_HOSTS
      - GROUP_NAME=endlessplanet
      - PROJECT_NAME=personal
      - BRANCH=master
      - USERNAME
      - EMAIL
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  pass:
    build: images/pass
    environment:
      - ID_RSA
      - KNOWN_HOSTS
      - GPG_PRIVATE_KEY
      - GPG_OWNER_TRUST
      - GPG_KEY_ID
      - USERNAME
      - EMAIL
  chromium:
    image: sassmann/debian-chromium
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse/native:/tmp/pulse
      - /dev/shm:/home/user/Download
    devices:
      - /dev/dri/card0 
    environment:
      - DISPLAY
  experiment:
    build: images/experiment
    environment:
      - PROJECT_NAME="experiment"